- hosts: all
  tasks:
    - name: get_state_for_bitcoin_client
      shell: bitcoin-cli getblockchaininfo
      register: result

    - name: bitcoin-cli getblochaininfo
      debug: var=result.stdout_lines
