- hosts: all
  vars_prompt:
    - name: tag_name
      prompt: 'please tag name'

  tasks:
    - name: remove_old_file
      file:
        path={{ item }}
        state=absent
      with_items:
        - /usr/local/bin/bench_bitcoin 
        - /usr/local/bin/bitcoin-cli
        - /usr/local/bin/bitcoind
        - /usr/local/bin/bi
        - ./git/bitcoin
        - ./.bitcoin
      become: yes

    - name: clone_{{ tag_name }}
      git:
        repo: 'https://github.com/bitcoin/bitcoin'
        dest: ./git/bitcoin
        version: '{{ tag_name }}'

    - name: autogen.sh
      shell: ./autogen.sh
      args:
        chdir: ./git/bitcoin

    - name: configure_without_gui&wallet
      shell: ./configure --without-gui --disable-wallet
      args:
        chdir: ./git/bitcoin

    - name: compile
      shell: make
      args:
        chdir: ./git/bitcoin

    - name: install_bitcoind
      shell: make install
      args:
        chdir: ./git/bitcoin
      become: yes

    - name: bitcoind_start
      shell: bitcoind -daemon